# -*- coding: utf-8 -*-
"""OlaMundo.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zv-ffjAgb4F3LFlY2kuScqsllJVAxhiJ
"""

print('olá mundo')